name: implicit_gs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile
  - python=3.9.18
  - pip
  - pytorch=2.0.1+cu118
  - tqdm
  - zCurve
  - pdb
  - pillow_heif
  - wandb
  - ipdb
  - pip:
    - submodules/diff-gaussian-rasterization_igs
    - submodules/simple-knn
